using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class listMechWeapon 
{
    public Dictionary<string,MechWeapon> listmechweapon;


    public listMechWeapon ()
    {
        listmechweapon.Add("Anti-Materiel_Rifle",new MechWeapon("Anti-Materiel Rifle",20,0,"Kinetic",new DiceRolls(2,6),0,"WIP"));
        listmechweapon.Add("Assault_Rifle", new MechWeapon("Assault Rifle", 10,0, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Charged_Blade", new MechWeapon("Charged blade", 0,1, "Energy", new DiceRolls(1,3,3), 0, "WIP"));
        listmechweapon.Add("Cylone_Pulse_Rifle", new MechWeapon("Cyclone pulse rifle", 15,0, "Kinetic", new DiceRolls(3, 6,3), 0, "WIP"));
        listmechweapon.Add("Heavy_Charged_Blade", new MechWeapon("heavy charged blade",0, 1, "Energy", new DiceRolls(1, 6,3), 0, "WIP"));
        listmechweapon.Add("Heavy_Machine_Gun", new MechWeapon("Heavy Machine gun",8,0, "Kinetic", new DiceRolls(2, 6,4), 0, "WIP"));
        listmechweapon.Add("Heavy_Melee_Weapon", new MechWeapon("Heavy Melee weapon ", 0,1, "Kinetic", new DiceRolls(2, 6,1), 0, "WIP"));
        listmechweapon.Add("Howitzer", new MechWeapon("Howitzer", 20,0, "Explosive", new DiceRolls(2, 6), 2, "WIP"));
        listmechweapon.Add("Hurricane_Cluster_Projector", new MechWeapon("Hurricane cluster projector", 10,0, "Explosive", new DiceRolls(1, 6,6),2, "WIP"));
        listmechweapon.Add("Missile_Rack", new MechWeapon("Missile Rack",10,0, "Explosive", new DiceRolls(1,3,1 ), 1, "WIP"));
        listmechweapon.Add("Mortar", new MechWeapon("Mortar", 15,0, "Explosive", new DiceRolls(1, 6,1), 1, "WIP"));
        listmechweapon.Add("Nexus(Hunter-killer)", new MechWeapon("Nexus (Hunter-Killer)",10,0, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Nexus(light)", new MechWeapon("Nexus(light)", 10,0, "Kinetic", new DiceRolls(1,3),0, "WIP"));
        listmechweapon.Add("Pistol", new MechWeapon("Pistol",5,3, "kinetic", new DiceRolls(1,3),0, "WIP"));
        listmechweapon.Add("Rocket-Propelled_Grenade", new MechWeapon("Rocket-Propelled Grenade",10,0, "Explosive", new DiceRolls(1, 6,1),2, "WIP"));
        listmechweapon.Add("Segment_knife", new MechWeapon("Segment_knife",0,1, "Energy", new DiceRolls(1,3,1), 0, "WIP"));
        listmechweapon.Add("Shotgun", new MechWeapon("Shotgun", 5, 3, "kinetic", new DiceRolls(1,6), 0, "WIP"));
        listmechweapon.Add("Tactical_knife", new MechWeapon("Tactical knife",0,1, "kinetic", new DiceRolls(1, 3,1), 0, "WIP"));
        listmechweapon.Add("Tactical_Melee_Weapon", new MechWeapon("Tactical Melee Weapon",0,1, "kinetic", new DiceRolls(1,6,2), 0, "WIP"));
        listmechweapon.Add("Tempest_Charged_Blade", new MechWeapon("Tempest Charged Blade",0,2, "Energy", new DiceRolls(3,6,4), 0, "WIP"));
        listmechweapon.Add("Thermal_Lance", new MechWeapon("Thermal Lance",10,10, "Energy", new DiceRolls(1,6,3), 0, "WIP"));
        listmechweapon.Add("Thermal_Pistol", new MechWeapon("thermal_Pistol", 5,5, "Energy", new DiceRolls(1,1,1), 0, "WIP"));
        listmechweapon.Add("Thermal_Rifle", new MechWeapon("Thermal_Rifle", 5, 0, "Energy", new DiceRolls(1, 3,2), 0, "WIP"));
        listmechweapon.Add("Assault_cannon", new MechWeapon("Assault_cannon",8,0, "Kinetic", new DiceRolls(1,6,2), 0, "WIP"));
        listmechweapon.Add("Blackspot_Targeting_laser", new MechWeapon("Blackspot Targeting Laser",15,0, "Energy", new DiceRolls(1, 3,1), 0, "WIP"));
        listmechweapon.Add("Bolt_Thrower", new MechWeapon("Bolt_Thrower",8,0, "Explosive", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Bristlecrown_Flechette_Launcher", new MechWeapon("Bristlecrown_Flechette_Launcher",1,1, "kinetic", new DiceRolls(1,1),1, "WIP"));
        listmechweapon.Add("Catalytic_Hammer", new MechWeapon("Catalytic Hammer",0,1, "kinetic", new DiceRolls(1, 3,5), 0, "WIP"));
        listmechweapon.Add("Chain_Axe", new MechWeapon("Chain Axe",0,1, "kinetic", new DiceRolls(1,6), 0, "WIP"));
        listmechweapon.Add("Combat_Drill", new MechWeapon("Combat Drill",0,1,"kinetic,Energy", new DiceRolls(3,6), 0, "WIP"));
        listmechweapon.Add("Concussion_Missiles", new MechWeapon("Concussion Missiles", 5, 0, "Explosive", new DiceRolls(1,3), 0, "WIP"));
        listmechweapon.Add("Cutter_MKII_Plasma_Torch", new MechWeapon("Cutter MKII Plasma Torch", 0,1, "Energy", new DiceRolls(1),1,1,0, "WIP"));
        listmechweapon.Add("DD288", new MechWeapon("DD288", 0,1, "Kinetic", new DiceRolls(1,6), 0, "WIP"));
        listmechweapon.Add("DD288_Charged", new MechWeapon("DD288 charged", 0, 1, "Explosive", new DiceRolls(4,6,8), 0, "WIP"));
        listmechweapon.Add("Daisy_cutter", new MechWeapon("Daisy cutter", 0, 1, "Kinetic", new DiceRolls(3,6), 0, "WIP"));
        listmechweapon.Add("Deck-Sweeper_Automatic_Shotgun", new MechWeapon("Deck-Sweeper Automatic Shotgun", 3,3, "Kinetic", new DiceRolls(2, 6), 0, "WIP"));
        listmechweapon.Add("HHS-155_Cannibal", new MechWeapon("HHS-155 Cannibal", 3,3, "Kinetic", new DiceRolls(2,6,4), 0, "WIP"));
        listmechweapon.Add("HHS-155_Cannibal_BB", new MechWeapon("HHS-155 Cannibal BB", 3, 3, "Kinetic", new DiceRolls(3, 6,4), 0, "WIP"));
        listmechweapon.Add("Hammer_U-RPL", new MechWeapon("Hammer U-RPL", 5, 0, "Explosive", new DiceRolls(2, 6, 3), 0, "WIP"));
        listmechweapon.Add("Hand_Cannon", new MechWeapon("Hand Cannon", 5, 3, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Impact_Lance", new MechWeapon("Impact Lance", 0, 3, "Energy", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Impaler_Nailgun", new MechWeapon("Impaler Nailgun", 5, 3, "Kinetic", new DiceRolls(1, 6,1), 0, "WIP"));
        listmechweapon.Add("Kinetic_Hammer", new MechWeapon("Kinetic Hammer",0,1, "Kinetic", new DiceRolls(2, 6,2), 0, "WIP"));
        listmechweapon.Add("Leviathan_Heavy_Assault_Cannon", new MechWeapon("Leviathan Heavy Assault Cannon", 8, 0, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Leviathan_Heavy_Assault_Cannon_Spin", new MechWeapon("Leviathan Heavy Assault Cannon Spin", 8, 0, "Kinetic", new DiceRolls(4,6,4), 0, "WIP"));
        listmechweapon.Add("Nanocarbon_Sword", new MechWeapon("Nanocarbon Sword", 0, 2, "Kinetic", new DiceRolls(1, 6,4), 0, "WIP"));
        listmechweapon.Add("Power_Knuckles", new MechWeapon("Power Knuckles", 0,1, "Explosive", new DiceRolls(1,3,1), 0, "WIP"));
        listmechweapon.Add("Tiger-Hunter_Combat_Sheathe", new MechWeapon("Tiger-Hunter Combat Sheathe", 0,1, "Kinetic", new DiceRolls(1,3,2), 0, "WIP"));
        listmechweapon.Add("War_Pike", new MechWeapon("War Pike", 0, 3, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Bolt_Nexus", new MechWeapon("Bolt Nexus", 10,0, "Energy", new DiceRolls(1), 0, "WIP"));
        listmechweapon.Add("Bolt_Nexus_TA", new MechWeapon("Bolt Nexus TA", 20, 0, "Energy", new DiceRolls(4), 0, "WIP"));
        listmechweapon.Add("Burst_Launcher", new MechWeapon("Busrt Laucher", 15, 0, "Explosive", new DiceRolls(1,3),1,0, 0, "WIP"));
        listmechweapon.Add("Ferrofluid_Lance", new MechWeapon("Ferrofluid Lance",0,2, "Kinetic", new DiceRolls(1,6), 0, "WIP"));
        listmechweapon.Add("Fold_Knife", new MechWeapon("Fold_Knife",0,1, "Kinetic", new DiceRolls(1,3), 0, "WIP"));
        listmechweapon.Add("Gandiva_Missiles", new MechWeapon("Gandiva Missiles", 15, 0, "Energy", new DiceRolls(1,6,3), 0, "WIP"));
        listmechweapon.Add("Kraul_Rifle", new MechWeapon("Kraul Rifle", 8, 0, "Kinetic", new DiceRolls(1,6), 0, "WIP"));
        listmechweapon.Add("Magnetic_Cannon", new MechWeapon("Magnetic Cannon",8, 0, "Energy", new DiceRolls(1,3,1), 0, "WIP"));
        listmechweapon.Add("Oracle_LMG-i", new MechWeapon("Oracle LMG-i", 15,0, "Kinetic", new DiceRolls(1,3), 0, "WIP"));
        listmechweapon.Add("Pinaka_Missiles", new MechWeapon("Pinaka Missiles", 20,0, "Explosive", new DiceRolls(2,6), 1, "WIP"));
        listmechweapon.Add("Rail_Rifle", new MechWeapon("Rail_Rifle", 10, 0, "Kinetic", new DiceRolls(1,6,1), 0, "WIP"));
        listmechweapon.Add("Rail_Gun", new MechWeapon("Rail Gun",20, 0, "Kinetic", new DiceRolls(1,6,4), 0, "WIP"));
        listmechweapon.Add("Retort_Loop_0", new MechWeapon("Retort Loop 0", 10, 0, "Kinetic", new DiceRolls(3), 0, "WIP"));
        listmechweapon.Add("Retort_Loop_1", new MechWeapon("Retort Loop 1", 10, 0, "Kinetic", new DiceRolls(1,6,3), 0, "WIP"));
        listmechweapon.Add("Retort_Loop_2", new MechWeapon("Retort Loop 2", 10, 0, "Kinetic", new DiceRolls(2, 6, 3), 0, "WIP"));
        listmechweapon.Add("Retort_Loop_3", new MechWeapon("Retort Loop 3", 10, 0, "Kinetic", new DiceRolls(3, 6, 3), 0, "WIP"));
        listmechweapon.Add("Sharenga_Missiles", new MechWeapon("Sharenga Missiles", 15, 0, "Explosive", new DiceRolls( 3), 0, "WIP"));
        listmechweapon.Add("Shock_Knife", new MechWeapon("Shock Knife", 0,1, "Energy", new DiceRolls(1),0,2, 0, "WIP"));
        listmechweapon.Add("Terashima_Blade", new MechWeapon("Terashima Blade", 0, 1, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Terashima_Blade_Troll", new MechWeapon("Terashima Blade Troll", 0, 1, "Kinetic", new DiceRolls(1, 6,3), 0, "WIP"));
        listmechweapon.Add("Terashima_Blade_Storm", new MechWeapon("Terashima Blade Storm", 0, 1, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Terashima_Blade_Lord", new MechWeapon("Terashima Blade Lord", 0, 1, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Terashima_Blade_Wind", new MechWeapon("Terashima Blade Wind", 0, 2, "Kinetic", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Variable_Sword", new MechWeapon("Variable Sword", 0,2, "Kinetic", new DiceRolls(3), 0, "WIP"));
        listmechweapon.Add("Veil_Rifle", new MechWeapon("Veil Rifle", 10, 0, "Energy", new DiceRolls(1,3,1), 0, "WIP"));
        listmechweapon.Add("Vijaya_Rockets", new MechWeapon("Vijaya Rockets", 5, 0, "Explosive", new DiceRolls(1, 3), 0, "WIP"));
        listmechweapon.Add("Vulture_DMR", new MechWeapon("Vulture DMR",15, 0, "Kinetic", new DiceRolls(1, 6,1), 0, "WIP"));
        listmechweapon.Add("Annihilation_Nexus", new MechWeapon("Annihilation Nexus", 0, 2, "Energy", new DiceRolls(1,6,3), 0, "WIP"));
        listmechweapon.Add("Arc_Projector", new MechWeapon("Arc Projector", 5,0, "Energy", new DiceRolls(1, 6,1), 0, "WIP"));
        listmechweapon.Add("Autogun", new MechWeapon("Autogun",15, 0, "Kinetic", new DiceRolls(3), 0, "WIP"));
        listmechweapon.Add("Autopod", new MechWeapon("Autopod",15, 0, "Kinetic", new DiceRolls(3), 0, "WIP"));
        listmechweapon.Add("Catalyst_Pistol", new MechWeapon("Catalyst Pistol", 0, 3, "Energy", new DiceRolls(1,3), 0, "WIP"));
        listmechweapon.Add("Fusion_Rifle", new MechWeapon("Fusion Rifle",6,0, "Energy", new DiceRolls(6), 0, "WIP"));
        listmechweapon.Add("Ghast_Nexus", new MechWeapon("Ghast Nexus", 10,0, "Explosive", new DiceRolls(1, 6,3), 0, "WIP"));
        listmechweapon.Add("Ghoul_Nexus", new MechWeapon("Ghoul Nexus", 10, 0, "Variable", new DiceRolls(1,3,2), 0, "WIP"));
        listmechweapon.Add("Mimic_Gun", new MechWeapon("Mimic Gun", 0,0, "Kinetic", new DiceRolls(1,2), 0, "WIP"));
        listmechweapon.Add("Nanobot_Whip", new MechWeapon("Nanobot Whip", 0,3, "Kinetic", new DiceRolls(2, 6), 0, "WIP"));
        listmechweapon.Add("Slag_Cannon", new MechWeapon("Slag Cannon",8,0, "Energy", new DiceRolls(1, 6), 0, "WIP"));
        listmechweapon.Add("Smartgun", new MechWeapon("Smartgun", 15,0, "Kinetic", new DiceRolls(4), 0, "WIP"));
        listmechweapon.Add("Swarm/Hive_Nanites", new MechWeapon("Swarm/Hive Nanites",5,0, "Kinetic", new DiceRolls(2),2,0, 0, "WIP"));
        listmechweapon.Add("unraveler", new MechWeapon("unraveler", 10,0, "Energy", new DiceRolls(2, 6), 0, "WIP"));
        listmechweapon.Add("Vorpal_Gun", new MechWeapon("Vorpal Gun",5, 0, "Kinetic", new DiceRolls(2, 6), 0, "WIP"));
        listmechweapon.Add("Andromeda-Pattern_Heavy_Laser_Rifle", new MechWeapon("Terashima Blade",12,0, "Energy", new DiceRolls(2, 6),0,3, 0, "WIP"));
        listmechweapon.Add("Annihilator", new MechWeapon("Annihilator",5, 3, "Energy", new DiceRolls(1,3,2), 0, "WIP"));
        listmechweapon.Add("Displacer", new MechWeapon("Displacer", 10,0, "Kinetic", new DiceRolls(10), 1, "WIP"));
        listmechweapon.Add("Gravity_Gun", new MechWeapon("Grabity Gun", 8,0, "Kinetic", new DiceRolls(1, 6),3, "WIP"));
        listmechweapon.Add("Krakatoa_Thermobaric_Flamethrower", new MechWeapon("Krakatoa Thermobaric Flamethrower",5, 0, "Energy", new DiceRolls(1),0,4 ,0, "WIP"));
        listmechweapon.Add("Plasma_Trower", new MechWeapon("Plasma Thrower",7,10, "Energy", new DiceRolls(1,6,2), 0,6, 0, "WIP"));
        listmechweapon.Add("Sol-Pattern_Laser_Rifle", new MechWeapon("Sol-Pattern Laser Rifle",8, 0, "Energy", new DiceRolls(1,6), 0, 1,0, "WIP"));
        listmechweapon.Add("ShatterHead_Colony_Missiles", new MechWeapon("ShatterHead Colony Missiles",15, 0, "Energy", new DiceRolls(1,3,1), 0, "WIP"));
        listmechweapon.Add("Siege_Cannon", new MechWeapon("Siege Cannon",30, 0, "Explosive", new DiceRolls(3,6),2, "WIP"));
        listmechweapon.Add("Siege_Cannon_Dir", new MechWeapon("Siege Cannon Direct",20, 0, "Explosive", new DiceRolls(3, 6), 0, "WIP"));
        listmechweapon.Add("Stub_Cannon", new MechWeapon("Stub Cannon",5, 0, "Explosive", new DiceRolls(3),0, "WIP"));
        listmechweapon.Add("Tachyon_Lance", new MechWeapon("Tachyon Lance",20, 0, "Energy", new DiceRolls(2, 6),0,8,0, "WIP"));
        listmechweapon.Add("Torch", new MechWeapon("Torch",0,1, "Energy", new DiceRolls(1, 6),0,3,0, "WIP"));
        listmechweapon.Add("Warp_Rifle", new MechWeapon("Warp Rifle", 10, 0, "Energy", new DiceRolls(1,3,1), 0, "WIP"));
    }
}
